builders:
  dirlist:
    import: "package:dirlist/dirlist.dart"
    builder_factories: ["DirlistGenerator.builder"]
    build_extensions: { ".dart": [".dirlist.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
